-- IED La Victoria — schema PostgreSQL en "proyecto-universidad".
-- Origen: proyecto-c/migrations/model/modelo.sql (MySQL), adaptado a Supabase.
-- Adaptaciones:
--   * Schema dedicado "proyecto-universidad" (el guion exige identificador citado)
--   * IDENTITY en lugar de AUTO_INCREMENT
--   * timestamptz en lugar de datetime
--   * usuario.auth_id para vincular con auth.users de Supabase
--   * usuario.contrasena queda como centinela (la clave vive en Supabase Auth)
--   * id serial en usuario_curso_vigencia para REST DELETE /:id
--   * curso.id y vigencia.id BY DEFAULT para permitir seeds con id explícito
--
-- Después de ejecutar: en Dashboard → Settings → API → Exposed schemas
-- agregue proyecto-universidad. Auth y Storage siguen en auth/storage.

CREATE SCHEMA IF NOT EXISTS "proyecto-universidad";

SET search_path TO "proyecto-universidad";

CREATE TABLE rol (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre varchar(30) UNIQUE NOT NULL,
  descripcion varchar(150)
);

CREATE TABLE permiso (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  codigo varchar(40) UNIQUE NOT NULL,
  nombre varchar(80) NOT NULL,
  descripcion varchar(255)
);

CREATE TABLE rol_permiso (
  id_rol integer NOT NULL REFERENCES rol (id) ON DELETE CASCADE,
  id_permiso integer NOT NULL REFERENCES permiso (id) ON DELETE CASCADE,
  PRIMARY KEY (id_rol, id_permiso)
);

CREATE TABLE estado (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre varchar(30) UNIQUE NOT NULL
);

CREATE TABLE usuario (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  auth_id uuid UNIQUE,
  identificacion varchar(20) UNIQUE NOT NULL,
  usuario varchar(20) UNIQUE NOT NULL,
  contrasena varchar(255) NOT NULL DEFAULT 'managed-by-supabase',
  nombre varchar(60) NOT NULL,
  apellido varchar(60) NOT NULL,
  email varchar(120) UNIQUE NOT NULL,
  id_estado integer NOT NULL REFERENCES estado (id),
  id_rol integer NOT NULL REFERENCES rol (id),
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_ultima_modificacion timestamptz
);

CREATE INDEX usuario_auth_id_idx ON usuario (auth_id);
CREATE INDEX usuario_id_rol_idx ON usuario (id_rol);
CREATE INDEX usuario_id_estado_idx ON usuario (id_estado);

CREATE TABLE curso (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grado varchar(20) NOT NULL
);

CREATE TABLE vigencia (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  CONSTRAINT vigencia_fechas_chk CHECK (fecha_fin > fecha_inicio)
);

CREATE TABLE usuario_curso_vigencia (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_curso integer NOT NULL REFERENCES curso (id),
  id_vigencia integer NOT NULL REFERENCES vigencia (id),
  id_usuario integer NOT NULL REFERENCES usuario (id),
  UNIQUE (id_curso, id_vigencia, id_usuario)
);

CREATE TABLE acudiente_estudiante (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_acudiente integer NOT NULL REFERENCES usuario (id),
  id_estudiante integer NOT NULL REFERENCES usuario (id),
  parentesco varchar(30),
  es_principal boolean NOT NULL DEFAULT true,
  UNIQUE (id_acudiente, id_estudiante)
);

CREATE TABLE configuracion (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  clave varchar(50) UNIQUE NOT NULL,
  valor varchar(255) NOT NULL,
  descripcion varchar(255)
);

CREATE TABLE auditoria (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES usuario (id),
  accion varchar(50) NOT NULL,
  entidad varchar(50) NOT NULL,
  id_entidad integer,
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  detalle varchar(255)
);

CREATE INDEX auditoria_usuario_idx ON auditoria (id_usuario);
CREATE INDEX auditoria_entidad_idx ON auditoria (entidad, id_entidad);
CREATE INDEX auditoria_fecha_idx ON auditoria (fecha_hora DESC);

CREATE TABLE estado_proceso (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre varchar(30) UNIQUE NOT NULL
);

CREATE TABLE motivo_resolucion (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre varchar(30) UNIQUE NOT NULL
);

CREATE TABLE archivo (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entidad_tipo varchar(30) NOT NULL,
  entidad_id integer NOT NULL,
  nombre_original varchar(150) NOT NULL,
  nombre_tecnico varchar(150) UNIQUE NOT NULL,
  ruta varchar(255) NOT NULL,
  es_confidencial boolean NOT NULL DEFAULT false,
  fecha_carga timestamptz NOT NULL DEFAULT now(),
  id_usuario_carga integer NOT NULL REFERENCES usuario (id)
);

CREATE INDEX archivo_entidad_idx ON archivo (entidad_tipo, entidad_id);

CREATE TABLE historial_proceso (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entidad_tipo varchar(30) NOT NULL,
  entidad_id integer NOT NULL,
  id_usuario_actua integer NOT NULL REFERENCES usuario (id),
  accion varchar(60) NOT NULL,
  observacion varchar(255),
  fecha_hora timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX historial_proceso_entidad_idx ON historial_proceso (entidad_tipo, entidad_id);

CREATE TABLE excusa (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  radicado varchar(30) UNIQUE NOT NULL,
  id_estudiante integer NOT NULL REFERENCES usuario (id),
  id_usuario_radica integer NOT NULL REFERENCES usuario (id),
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  motivo_descripcion varchar(255) NOT NULL,
  fecha_radicado timestamptz NOT NULL DEFAULT now(),
  fecha_limite_edicion timestamptz NOT NULL,
  id_estado_proceso integer NOT NULL REFERENCES estado_proceso (id),
  id_motivo_resolucion integer REFERENCES motivo_resolucion (id),
  observaciones_revision varchar(255),
  id_usuario_reviso integer REFERENCES usuario (id),
  fecha_revision timestamptz,
  CONSTRAINT excusa_fechas_chk CHECK (fecha_fin >= fecha_inicio)
);

CREATE INDEX excusa_estudiante_idx ON excusa (id_estudiante);
CREATE INDEX excusa_estado_idx ON excusa (id_estado_proceso);

CREATE TABLE clasificacion_convivencia (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre varchar(20) UNIQUE NOT NULL,
  descripcion varchar(150)
);

CREATE TABLE situacion_convivencia (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_estudiante integer NOT NULL REFERENCES usuario (id),
  fecha_hora date NOT NULL,
  lugar varchar(120),
  descripcion_objetiva varchar(500) NOT NULL,
  id_clasificacion integer NOT NULL REFERENCES clasificacion_convivencia (id),
  id_estado_proceso integer NOT NULL REFERENCES estado_proceso (id),
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  id_usuario_creo integer NOT NULL REFERENCES usuario (id)
);

CREATE TABLE situacion_reportante (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_situacion integer NOT NULL REFERENCES situacion_convivencia (id) ON DELETE CASCADE,
  id_usuario_reporta integer NOT NULL REFERENCES usuario (id),
  rol_en_reporte varchar(60)
);

CREATE TABLE actuacion_convivencia (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_situacion integer NOT NULL REFERENCES situacion_convivencia (id) ON DELETE CASCADE,
  descripcion varchar(500) NOT NULL,
  id_responsable integer NOT NULL REFERENCES usuario (id),
  fecha_compromiso date,
  fecha_cumplimiento date,
  cumplido boolean NOT NULL DEFAULT false,
  fecha_registro timestamptz NOT NULL DEFAULT now(),
  id_usuario_registro integer NOT NULL REFERENCES usuario (id)
);

CREATE TABLE remision_orientacion (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_situacion integer NOT NULL REFERENCES situacion_convivencia (id) ON DELETE CASCADE,
  numero_remision varchar(30) UNIQUE NOT NULL,
  motivo_atencion varchar(500) NOT NULL,
  activada boolean NOT NULL DEFAULT false,
  fecha_activacion timestamptz,
  fecha_generacion timestamptz,
  ruta_pdf varchar(255),
  id_usuario_genera integer NOT NULL REFERENCES usuario (id)
);

COMMENT ON TABLE rol IS '1 Administrador (TI) - control total, único con CRUD de usuarios. 2 Coordinador. 3 Docente/Psicorientador combinado. 4 Estudiante. 5 Acudiente.';
COMMENT ON TABLE usuario IS 'Solo Administrador tiene CRUD completo. auth_id vincula con Supabase Auth.';
COMMENT ON TABLE usuario_curso_vigencia IS 'Matrícula (estudiante) o asignación (docente) por vigencia. Distinción por rol del usuario.';
COMMENT ON TABLE auditoria IS 'Log de seguridad: login, CRUD, consultas confidenciales, descargas, PDF.';
COMMENT ON TABLE archivo IS 'Anexos polimórficos: entidad_tipo = EXCUSA | SITUACION_CONVIVENCIA.';
COMMENT ON TABLE historial_proceso IS 'Línea de tiempo funcional, distinta de auditoria.';
COMMENT ON TABLE excusa IS 'fecha_limite_edicion se calcula en servidor. Coordinador diligencia revisión.';
COMMENT ON TABLE situacion_convivencia IS 'Tipo III exige actuaciones inmediatas fuera del sistema.';

-- Nest usa la service_role key. Auth y Storage permanecen fuera de este schema.
GRANT USAGE ON SCHEMA "proyecto-universidad" TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA "proyecto-universidad" TO postgres, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA "proyecto-universidad" TO postgres, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA "proyecto-universidad" TO postgres, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA "proyecto-universidad"
  GRANT ALL ON TABLES TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA "proyecto-universidad"
  GRANT ALL ON SEQUENCES TO postgres, service_role;
